/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ChatLieu;
import Model.MauSac;
import Model.SanPhamCT;
import Model.XuatXu;
import Repository.Xdate;
import Service.ChatLieuDao;
import Service.MauSacDao;
import Service.SanPhamDAO;
import Service.XuatXuDao;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xuan Dat
 */
public class SanPhamCTView extends javax.swing.JFrame {

    DefaultTableModel mol = new DefaultTableModel();
    SanPhamDAO service = new SanPhamDAO();
    XuatXuDao daoxx = new XuatXuDao();
    MauSacDao daoms = new MauSacDao();
    ChatLieuDao daocl = new ChatLieuDao();

    List<XuatXu> listXuatXu;
    List<MauSac> listMauSac;
    List<ChatLieu> listChatLieu;
    List<SanPhamCT> listSPCT;

    String maVi;

    public SanPhamCTView(String maVi, String tenVi) {
        initComponents();
        init();
        this.maVi = maVi;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txt_tenSP.setText(tenVi);
        this.fillTable(service.getDaTaSPCT(maVi));

        // Kiểm tra sản phẩm đã có thông tin chi tiết chưa 
        if (service.getSoLuongSPCT(maVi) <= 0) {
            System.out.println("Sản phẩm chưa có thông tin chi tiết");
        } else {
            // Sản phẩm đã có thông tin chi tiết 
            SanPhamCT sanPhamCT = service.getDaTaSPCT(maVi).get(0);
            txt_MaCTVi.setText(sanPhamCT.getMaCTSP());
            txt_KhoaVi.setText(sanPhamCT.getKhoaVi());
            txt_SoLuong.setText(String.valueOf(sanPhamCT.getSoLuongSP()));
            txt_soNganDungThe.setText(sanPhamCT.getSoNgan());
            txt_NgayNhap.setDate(Xdate.toDate(sanPhamCT.getNgayNhap(), "yyyy-MM-dd"));
            txt_giaBan.setText(String.valueOf(sanPhamCT.getGiaBanSP()));
            txt_giaNhap.setText(String.valueOf(sanPhamCT.getGiaNhapSP()));
        }
    }

    private SanPhamCTView() {
        initComponents();
        init();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void init() {
        fillcomboboxXuatXu();
        fillcomboboxMauSac();
        fillcomboboxChatLieu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientColorCustomKH1 = new ColorGradient2D.GradientColorCustomKH();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_tenSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_MaCTVi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbo_mauSac = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_chatLieu = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboxuatXu = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbo_loaiVi = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_KhoaVi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_soNganDungThe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_NgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_giaNhap = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SanPhamCT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gradientColorCustomKH1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Chi Tiết Sản Phẩm");
        gradientColorCustomKH1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tên Ví ");
        gradientColorCustomKH1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 63, -1, -1));

        txt_tenSP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_tenSP.setForeground(new java.awt.Color(255, 51, 51));
        txt_tenSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tenSP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_tenSP.setEnabled(false);
        gradientColorCustomKH1.add(txt_tenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 58, 203, 28));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã Chi Tiết Ví ");
        gradientColorCustomKH1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, -1, -1));

        txt_MaCTVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_MaCTVi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_MaCTVi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_MaCTVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 105, 203, 28));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Màu Sắc");
        gradientColorCustomKH1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 153, -1, -1));

        cbo_mauSac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_mauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 147, 146, 28));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 148, 30, 27));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Chất Liệu");
        gradientColorCustomKH1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 199, -1, -1));

        cbo_chatLieu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_chatLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 193, 147, 28));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 193, 30, 27));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Xuất Xứ");
        gradientColorCustomKH1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 63, -1, -1));

        cboxuatXu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cboxuatXu, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 57, 146, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 57, 30, 27));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Loại Ví");
        gradientColorCustomKH1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 110, -1, -1));

        cbo_loaiVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_loaiVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 104, 146, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        gradientColorCustomKH1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 106, 30, 27));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Khóa Ví");
        gradientColorCustomKH1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 152, -1, -1));

        txt_KhoaVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_KhoaVi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_KhoaVi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_KhoaVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 147, 211, 28));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Số Ngăn đựng Thẻ");
        gradientColorCustomKH1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 248, -1, -1));

        txt_soNganDungThe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_soNganDungThe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_soNganDungThe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_soNganDungThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 243, 204, 28));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Số Lượng");
        gradientColorCustomKH1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 198, -1, -1));

        txt_SoLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_SoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_SoLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 193, 211, 28));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Ngày Nhập");
        gradientColorCustomKH1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 248, -1, -1));
        gradientColorCustomKH1.add(txt_NgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 239, 209, 32));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Giá Bán");
        gradientColorCustomKH1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 300, -1, -1));

        txt_giaBan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_giaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_giaBan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_giaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 289, 204, 28));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Giá Nhập");
        gradientColorCustomKH1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 294, -1, -1));

        txt_giaNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_giaNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_giaNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_giaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 289, 209, 28));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        jButton6.setText("Sửa");
        gradientColorCustomKH1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        jButton7.setText("Xóa");
        gradientColorCustomKH1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-reset-24.png"))); // NOI18N
        jButton8.setText("Làm mới");
        gradientColorCustomKH1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        tbl_SanPhamCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SPCT", "Màu Sắc", "Chất Liệu", "Xuất Xứ", "Loại Ví", "Khóa Ví", "Số Ngăn", "Số Lượng", "Giá Nhập", "Giá Bán", "Ngày Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_SanPhamCT);

        gradientColorCustomKH1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 850, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradientColorCustomKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientColorCustomKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Quản lý xuất xứ sản phẩm 
        new XuatXuJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Quản lý màu sắc sản phẩm 
        new MauSacJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Quản lý chất liệu 
        new ChatLieuJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamCTView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_chatLieu;
    private javax.swing.JComboBox<String> cbo_loaiVi;
    private javax.swing.JComboBox<String> cbo_mauSac;
    private javax.swing.JComboBox<String> cboxuatXu;
    private ColorGradient2D.GradientColorCustomKH gradientColorCustomKH1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SanPhamCT;
    private javax.swing.JTextField txt_KhoaVi;
    private javax.swing.JTextField txt_MaCTVi;
    private com.toedter.calendar.JDateChooser txt_NgayNhap;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_soNganDungThe;
    private javax.swing.JTextField txt_tenSP;
    // End of variables declaration//GEN-END:variables

    private void fillTable(List<SanPhamCT> list) {
        mol = (DefaultTableModel) tbl_SanPhamCT.getModel();
        mol.setRowCount(0);
        for (SanPhamCT x : list) {
            mol.addRow(new Object[]{
                x.getMaCTSP(),
                x.getTenMauSac(),
                x.getTenChatLieu(),
                x.getTenXuatXu(),
                x.getTenLoaiVi(),
                x.getKhoaVi(),
                x.getSoNgan(),
                x.getSoLuongSP(),
                x.getGiaNhapSP(),
                x.getGiaBanSP(),
                x.getNgayNhap()
            });
        }
    }

    private void fillcomboboxXuatXu() {
        DefaultComboBoxModel modelxx = (DefaultComboBoxModel) cboxuatXu.getModel();
        modelxx.removeAllElements();
        listXuatXu = daoxx.selectAll();
        for (XuatXu x : listXuatXu) {
            modelxx.addElement(x.getTenXuatXu());
        }
    }

    private void fillcomboboxMauSac() {
        DefaultComboBoxModel modelMausac = (DefaultComboBoxModel) cbo_mauSac.getModel();
        modelMausac.removeAllElements();
        listMauSac = daoms.selectAll();
        for (MauSac x : listMauSac) {
            modelMausac.addElement(x.getTenMauSac());
        }
    }

    private void fillcomboboxChatLieu() {
        DefaultComboBoxModel modelChat = (DefaultComboBoxModel) cbo_chatLieu.getModel();
        modelChat.removeAllElements();
        listChatLieu = daocl.selectAll();
        for (ChatLieu x : listChatLieu) {
            modelChat.addElement(x.getTenChatLieu());
        }
    }

}
