/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ChatLieu;
import Model.LoaiVi;
import Model.MauSac;
import Model.SanPham;
import Model.SanPhamCT;
import Model.Vi;
import Model.XuatXu;
import Repository.MsgBox;
import Repository.Xdate;
import Service.ChatLieuDao;
import Service.LoaiViDao;
import Service.MauSacDao;
import Service.SanPhamDAO;
import Service.SanPhamService;
import Service.ThuocTinhSanPhamDAO;
import Service.XuatXuDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xuan Dat
 */
public class SanPhamCTView extends javax.swing.JFrame {

    DefaultTableModel mol = new DefaultTableModel();
    SanPhamDAO service = new SanPhamDAO();
    XuatXuDao daoxx = new XuatXuDao();
    MauSacDao daoms = new MauSacDao();
    ChatLieuDao daocl = new ChatLieuDao();
    LoaiViDao daolv = new LoaiViDao();
    ThuocTinhSanPhamDAO serviceTT = new ThuocTinhSanPhamDAO();

    List<XuatXu> listXuatXu;
    List<MauSac> listMauSac;
    List<ChatLieu> listChatLieu;
    List<LoaiVi> listLoaiVi;
    List<SanPhamCT> listSPCT;
    String maVi;

    public SanPhamCTView(String maVi, String tenVi) {
        initComponents();
        init();
        this.maVi = maVi;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txt_tenSP.setText(tenVi);
        this.fillTable(service.getDaTaSPCT(maVi));

        // Kiểm tra sản phẩm đã có thông tin chi tiết chưa 
        if (service.getSoLuongSPCT(maVi) <= 0) {
            //System.out.println("Sản phẩm chưa có thông tin chi tiết");
        }
    }

    private SanPhamCTView() {
        initComponents();
        init();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void init() {
        fillcomboboxXuatXu();
        fillcomboboxMauSac();
        fillcomboboxChatLieu();
        fillcomboboxLoaiVi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientColorCustomKH1 = new ColorGradient2D.GradientColorCustomKH();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_tenSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_MaCTVi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbo_mauSac = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_chatLieu = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbo_xuatXu = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbo_loaiVi = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_KhoaVi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_soNganDungThe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_NgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_giaNhap = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SanPhamCT = new javax.swing.JTable();
        btnSua1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gradientColorCustomKH1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Chi Tiết Sản Phẩm");
        gradientColorCustomKH1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tên Ví ");
        gradientColorCustomKH1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 63, -1, -1));

        txt_tenSP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_tenSP.setForeground(new java.awt.Color(255, 51, 51));
        txt_tenSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tenSP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_tenSP.setEnabled(false);
        gradientColorCustomKH1.add(txt_tenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 58, 203, 28));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã Chi Tiết Ví ");
        gradientColorCustomKH1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, -1, -1));

        txt_MaCTVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_MaCTVi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_MaCTVi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_MaCTVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 105, 203, 28));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Màu Sắc");
        gradientColorCustomKH1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 153, -1, -1));

        cbo_mauSac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_mauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 147, 146, 28));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 148, 30, 27));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Chất Liệu");
        gradientColorCustomKH1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 199, -1, -1));

        cbo_chatLieu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_chatLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 193, 147, 28));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 193, 30, 27));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Xuất Xứ");
        gradientColorCustomKH1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 63, -1, -1));

        cbo_xuatXu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_xuatXu, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 57, 146, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 57, 30, 27));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Loại Ví");
        gradientColorCustomKH1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 110, -1, -1));

        cbo_loaiVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gradientColorCustomKH1.add(cbo_loaiVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 104, 146, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 106, 30, 27));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Khóa Ví");
        gradientColorCustomKH1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 152, -1, -1));

        txt_KhoaVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_KhoaVi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_KhoaVi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_KhoaVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 147, 211, 28));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Số Ngăn đựng Thẻ");
        gradientColorCustomKH1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 248, -1, -1));

        txt_soNganDungThe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_soNganDungThe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_soNganDungThe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_soNganDungThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 243, 204, 28));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Số Lượng");
        gradientColorCustomKH1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 198, -1, -1));

        txt_SoLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_SoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_SoLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 193, 211, 28));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Ngày Nhập");
        gradientColorCustomKH1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 248, -1, -1));
        gradientColorCustomKH1.add(txt_NgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 239, 209, 32));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Giá Bán");
        gradientColorCustomKH1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 300, -1, -1));

        txt_giaBan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_giaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_giaBan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_giaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 289, 204, 28));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Giá Nhập");
        gradientColorCustomKH1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 294, -1, -1));

        txt_giaNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_giaNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_giaNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gradientColorCustomKH1.add(txt_giaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 289, 209, 28));

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-reset-24.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        tbl_SanPhamCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SPCT", "Màu Sắc", "Chất Liệu", "Xuất Xứ", "Loại Ví", "Khóa Ví", "Số Ngăn", "Số Lượng", "Giá Nhập", "Giá Bán", "Ngày Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SanPhamCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamCTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SanPhamCT);

        gradientColorCustomKH1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 850, 210));

        btnSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        btnSua1.setText("Thêm");
        btnSua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSua1MouseClicked(evt);
            }
        });
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });
        gradientColorCustomKH1.add(btnSua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradientColorCustomKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientColorCustomKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Quản lý xuất xứ sản phẩm 
        new XuatXuJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Quản lý màu sắc sản phẩm 
        new MauSacJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Quản lý chất liệu 
        new ChatLieuJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new LoaiViJDiaLog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lammoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here

    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbl_SanPhamCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamCTMouseClicked
        // Click hiện thông tin chi tiết sản phẩm lên form 
        // Sản phẩm đã có thông tin chi tiết 
        int index = tbl_SanPhamCT.getSelectedRow();
        SanPhamCT sanPhamCT = service.getDaTaSPCT(maVi).get(index);
        txt_MaCTVi.setText(sanPhamCT.getMaCTSP());
        txt_KhoaVi.setText(sanPhamCT.getKhoaVi());
        txt_SoLuong.setText(String.valueOf(sanPhamCT.getSoLuongSP()));
        txt_soNganDungThe.setText(sanPhamCT.getSoNgan());
        txt_NgayNhap.setDate(Xdate.toDate(sanPhamCT.getNgayNhap(), "yyyy-MM-dd"));
        txt_giaBan.setText(String.valueOf(sanPhamCT.getGiaBanSP()));
        txt_giaNhap.setText(String.valueOf(sanPhamCT.getGiaNhapSP()));
        cbo_xuatXu.setSelectedItem(sanPhamCT.getTenXuatXu());
        cbo_loaiVi.setSelectedItem(sanPhamCT.getTenLoaiVi());
        cbo_mauSac.setSelectedItem(sanPhamCT.getTenMauSac());
        cbo_chatLieu.setSelectedItem(sanPhamCT.getTenChatLieu());

//        txt_MaCTVi.setEnabled(false);
    }//GEN-LAST:event_tbl_SanPhamCTMouseClicked

    private void btnSua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSua1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1MouseClicked

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // Thêm chi tiết sản phẩm 
        this.insert();
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void lammoi() {
        txt_MaCTVi.setText("");
        txt_KhoaVi.setText("");
        txt_NgayNhap.setDateFormatString("");
        txt_SoLuong.setText("");
        txt_giaBan.setText("");
        txt_giaNhap.setText("");
        txt_soNganDungThe.setText("");
        txt_MaCTVi.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamCTView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamCTView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JComboBox<String> cbo_chatLieu;
    private javax.swing.JComboBox<String> cbo_loaiVi;
    private javax.swing.JComboBox<String> cbo_mauSac;
    private javax.swing.JComboBox<String> cbo_xuatXu;
    private ColorGradient2D.GradientColorCustomKH gradientColorCustomKH1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SanPhamCT;
    private javax.swing.JTextField txt_KhoaVi;
    private javax.swing.JTextField txt_MaCTVi;
    private com.toedter.calendar.JDateChooser txt_NgayNhap;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_soNganDungThe;
    private javax.swing.JTextField txt_tenSP;
    // End of variables declaration//GEN-END:variables

    private void fillTable(List<SanPhamCT> list) {
        mol = (DefaultTableModel) tbl_SanPhamCT.getModel();
        mol.setRowCount(0);
        for (SanPhamCT x : list) {
            mol.addRow(new Object[]{
                x.getMaCTSP(),
                x.getTenMauSac(),
                x.getTenChatLieu(),
                x.getTenXuatXu(),
                x.getTenLoaiVi(),
                x.getKhoaVi(),
                x.getSoNgan(),
                x.getSoLuongSP(),
                x.getGiaNhapSP(),
                x.getGiaBanSP(),
                x.getNgayNhap()
            });
        }
    }

    private void fillcomboboxXuatXu() {
        DefaultComboBoxModel modelxx = (DefaultComboBoxModel) cbo_xuatXu.getModel();
        modelxx.removeAllElements();
        listXuatXu = daoxx.selectAll();
        for (XuatXu x : listXuatXu) {
            modelxx.addElement(x.getTenXuatXu());
        }
    }

    private void fillcomboboxMauSac() {
        DefaultComboBoxModel modelMausac = (DefaultComboBoxModel) cbo_mauSac.getModel();
        modelMausac.removeAllElements();
        listMauSac = daoms.selectAll();
        for (MauSac x : listMauSac) {
            modelMausac.addElement(x.getTenMauSac());
        }
    }

    private void fillcomboboxChatLieu() {
        DefaultComboBoxModel modelChat = (DefaultComboBoxModel) cbo_chatLieu.getModel();
        modelChat.removeAllElements();
        listChatLieu = daocl.selectAll();
        for (ChatLieu x : listChatLieu) {
            modelChat.addElement(x.getTenChatLieu());
        }
    }

    private void fillcomboboxLoaiVi() {
        DefaultComboBoxModel modelChat = (DefaultComboBoxModel) cbo_loaiVi.getModel();
        modelChat.removeAllElements();
        listLoaiVi = daolv.selectAll();
        for (LoaiVi lv : listLoaiVi) {
            modelChat.addElement(lv.getTenLoaiVi());
        }
    }

    private boolean vadidateNull() {
        List<SanPhamCT> list = service.getDaTaSPCT(maVi);
        String id = txt_MaCTVi.getText();
        String tensp = txt_tenSP.getText();
        Integer soLuong = Integer.parseInt(txt_SoLuong.getText());
        Double giaNhap = Double.parseDouble(txt_giaNhap.getText());
        Double giaBan = Double.parseDouble(txt_giaBan.getText());
        if (txt_MaCTVi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sản phẩm!");
            txt_MaCTVi.requestFocus();

            return false;
        } else if (txt_KhoaVi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập khóa sản phẩm!");
            return false;
        } else if (txt_SoLuong.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng sản phẩm!");
            return false;
        } else if (txt_giaNhap.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập sản phẩm!");
            return false;
        } else if (txt_giaBan.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán sản phẩm!");
            return false;
        } else if (txt_soNganDungThe.getText() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số ngăn đựng thẻ!");
            return false;
        } else if (txt_NgayNhap.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày nhập sản phẩm!");
            return false;
        } else if (txt_MaCTVi.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm phải trên 4 kí tự");
            return false;
        } else if (txt_tenSP.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm phải trên 5 kí tự");
            return false;
        } else if (soLuong < 1) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải trên 1 sản phẩm");
            return false;
        } else if (giaNhap < 1) {
            JOptionPane.showMessageDialog(this, "Giá nhập sản phẩm phải trên 0");
            return false;
        } else if (giaBan < 0) {
            JOptionPane.showMessageDialog(this, "Giá bán sản phẩm phải trên 0");
            return false;
        } else if (txt_tenSP.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm phải trên 5 kí tự");
            return false;
        }
        return true;
//return true;
    }

    // Check trùng sản phẩm 
    private boolean VadidateTrungCTSP() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String maCTSP = txt_MaCTVi.getText();
            String khoaVi = txt_KhoaVi.getText();
            String soNganDungThe = txt_soNganDungThe.getText();
            String MauSac = (String) cbo_mauSac.getSelectedItem();
            String ChatLieu = (String) cbo_chatLieu.getSelectedItem();
            String XuatXu = (String) cbo_xuatXu.getSelectedItem();
            String LoaiVi = (String) cbo_loaiVi.getSelectedItem();
            int soLuong = Integer.parseInt(txt_SoLuong.getText());
            String ngayNhap = dateFormat.format(txt_NgayNhap.getDate());
            Double giaNhap = Double.valueOf(txt_giaNhap.getText());
            Double giaBan = Double.valueOf(txt_giaBan.getText());
            for (SanPhamCT x : service.getDaTaSPCT(maVi)) {
                if (maCTSP.equalsIgnoreCase(x.getMaCTSP())
                        & khoaVi.equalsIgnoreCase(x.getKhoaVi())
                        & soLuong == x.getSoLuongSP()
                        & soNganDungThe.equalsIgnoreCase(x.getSoNgan())
                        & ngayNhap.equalsIgnoreCase(x.getNgayNhap())
                        & giaNhap == x.getGiaNhapSP()
                        & giaBan == x.getGiaBanSP()
                        & MauSac.equalsIgnoreCase(x.getTenMauSac())
                        & ChatLieu.equalsIgnoreCase(x.getTenChatLieu())
                        & XuatXu.equalsIgnoreCase(x.getTenXuatXu())
                        & LoaiVi.equalsIgnoreCase(x.getTenLoaiVi())) {
                    JOptionPane.showMessageDialog(this, "Chi tiết sản phẩm đã tồn tại");
                    return false;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhập đủ thông tin !");
        }
        return true;
    }

    private void insert() {
        if (VadidateTrungCTSP() & vadidateNull()) {
            try {
                int idSP, idMauSac, idChatLieu, idXuatXu, idLoaiVi, soLuong;
                String maCTSP, khoaVi, soNganDungThe, ngayNhap;
                double giaBan, giaNhap;
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                idSP = serviceTT.getIDSPbyName(txt_tenSP.getText());
                idMauSac = serviceTT.getIDMauSacbyName((String) cbo_mauSac.getSelectedItem());
                idChatLieu = serviceTT.getIDChatLieubyName((String) cbo_chatLieu.getSelectedItem());
                idXuatXu = serviceTT.getIDXuatXubyName((String) cbo_xuatXu.getSelectedItem());
                idLoaiVi = serviceTT.getIDLoaiVibyName((String) cbo_loaiVi.getSelectedItem());
                maCTSP = txt_MaCTVi.getText();
                khoaVi = txt_KhoaVi.getText();
                soNganDungThe = txt_soNganDungThe.getText();
                ngayNhap = dateFormat.format(txt_NgayNhap.getDate());
                soLuong = Integer.valueOf(txt_SoLuong.getText());
                giaNhap = Double.valueOf(txt_giaNhap.getText());
                giaBan = Double.valueOf(txt_giaBan.getText());
                service.addCTSP(idSP, idMauSac, idChatLieu, idXuatXu, idLoaiVi, maCTSP, khoaVi, soNganDungThe, soLuong, giaNhap, giaBan, ngayNhap);
                JOptionPane.showMessageDialog(this, "Thêm chi tiết sản phẩm thành công");
                this.fillTable(service.getDaTaSPCT(maVi));
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin ");
            }

        }

    }

    private void update() {
        int idSP, idMauSac, idChatLieu, idXuatXu, idLoaiVi, soLuong;
        String maCTSP, khoaVi, soNganDungThe, ngayNhap;
        double giaBan, giaNhap;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        idSP = serviceTT.getIDSPbyName(txt_tenSP.getText());
        idMauSac = serviceTT.getIDMauSacbyName((String) cbo_mauSac.getSelectedItem());
        idChatLieu = serviceTT.getIDChatLieubyName((String) cbo_chatLieu.getSelectedItem());
        idXuatXu = serviceTT.getIDXuatXubyName((String) cbo_xuatXu.getSelectedItem());
        idLoaiVi = serviceTT.getIDLoaiVibyName((String) cbo_loaiVi.getSelectedItem());
        maCTSP = txt_MaCTVi.getText();
        khoaVi = txt_KhoaVi.getText();
        soNganDungThe = txt_soNganDungThe.getText();
        ngayNhap = dateFormat.format(txt_NgayNhap.getDate());
        soLuong = Integer.valueOf(txt_SoLuong.getText());
        giaNhap = Double.valueOf(txt_giaNhap.getText());
        giaBan = Double.valueOf(txt_giaBan.getText());
        try {
            if (MsgBox.confirm(this, "Bạn có muốn sửa sản phẩm ?")) {
                service.updateCTSP(idSP, idMauSac, idChatLieu, idXuatXu, idLoaiVi, maCTSP, khoaVi, soNganDungThe, soLuong, giaNhap, giaBan, ngayNhap);
                this.fillTable(service.getDaTaSPCT(maVi));
                JOptionPane.showMessageDialog(this, "Đã sửa");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ops! Sửa thất bại");
            e.printStackTrace();
        }
    }

    private SanPhamCT getInformation() {
        SanPhamCT sp = new SanPhamCT();
        sp.setMaCTSP(txt_MaCTVi.getText());
        sp.setGiaBanSP(Double.parseDouble(txt_giaBan.getText()));
        sp.setGiaNhapSP(Double.parseDouble(txt_giaNhap.getText()));
        sp.setSoLuongSP(Integer.parseInt(txt_SoLuong.getText()));

//        sp.setTenChatLieu(daocl.selectIdByName(cbo_chatLieu.getSelectedItem() + ""));
//        sp.setTenLoaiVi(daolv.selectIdByName(cbo_loaiVi.getSelectedItem() + ""));
//
//        sp.setTenMauSac(daoms.selectIdByName(cbo_mauSac.getSelectedItem() + ""));
//
//        sp.setTenXuatXu(daoxx.selectIdByName(cbo_xuatXu.getSelectedItem() + ""));
        sp.setKhoaVi(txt_KhoaVi.getText());
        sp.setNgayNhap(txt_NgayNhap.getDateFormatString());
        sp.setSoNgan(txt_soNganDungThe.getText());
        return sp;
    }

}
