/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template 
*/
package View;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setColor(lbl_Trangchu);
        setColorJpanel(Trangchu);
        showPanel(new TrangChuView());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Trangchu = new javax.swing.JPanel();
        lbl_Trangchu = new javax.swing.JLabel();
        BanHang = new javax.swing.JPanel();
        lbl_BanHang = new javax.swing.JLabel();
        SanPham = new javax.swing.JPanel();
        lbl_SanPham = new javax.swing.JLabel();
        HoaDon = new javax.swing.JPanel();
        lbl_HoaDon = new javax.swing.JLabel();
        NhanVien = new javax.swing.JPanel();
        lbl_NhanVien = new javax.swing.JLabel();
        KhachHang = new javax.swing.JPanel();
        lbl_KhachHang = new javax.swing.JLabel();
        KhuyenMai = new javax.swing.JPanel();
        lbl_KhuyenMai = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        lbl_thongke = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Show = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng BoLyBop");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1170, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 186, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(214, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/use.png"))); // NOI18N

        Trangchu.setBackground(new java.awt.Color(73, 186, 245));

        lbl_Trangchu.setBackground(new java.awt.Color(73, 186, 245));
        lbl_Trangchu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Trangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Trangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hom.png"))); // NOI18N
        lbl_Trangchu.setText("Trang chủ");
        lbl_Trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TrangchuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TrangchuLayout = new javax.swing.GroupLayout(Trangchu);
        Trangchu.setLayout(TrangchuLayout);
        TrangchuLayout.setHorizontalGroup(
            TrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangchuLayout.createSequentialGroup()
                .addComponent(lbl_Trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TrangchuLayout.setVerticalGroup(
            TrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        BanHang.setBackground(new java.awt.Color(73, 186, 245));
        BanHang.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_BanHang.setBackground(new java.awt.Color(73, 186, 245));
        lbl_BanHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_BanHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sell.png"))); // NOI18N
        lbl_BanHang.setText("Bán hàng");
        lbl_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BanHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BanHangLayout = new javax.swing.GroupLayout(BanHang);
        BanHang.setLayout(BanHangLayout);
        BanHangLayout.setHorizontalGroup(
            BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanHangLayout.createSequentialGroup()
                .addComponent(lbl_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BanHangLayout.setVerticalGroup(
            BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        SanPham.setBackground(new java.awt.Color(73, 186, 245));
        SanPham.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_SanPham.setBackground(new java.awt.Color(73, 186, 245));
        lbl_SanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SanPham.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-wallet-32.png"))); // NOI18N
        lbl_SanPham.setText("Sản Phẩm");
        lbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addComponent(lbl_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_SanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        HoaDon.setBackground(new java.awt.Color(73, 186, 245));
        HoaDon.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_HoaDon.setBackground(new java.awt.Color(73, 186, 245));
        lbl_HoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_HoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill.png"))); // NOI18N
        lbl_HoaDon.setText("Hóa Đơn");
        lbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addComponent(lbl_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        NhanVien.setBackground(new java.awt.Color(73, 186, 245));
        NhanVien.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_NhanVien.setBackground(new java.awt.Color(73, 186, 245));
        lbl_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-staff-32.png"))); // NOI18N
        lbl_NhanVien.setText("Nhân Viên");
        lbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        KhachHang.setBackground(new java.awt.Color(73, 186, 245));
        KhachHang.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_KhachHang.setBackground(new java.awt.Color(73, 186, 245));
        lbl_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_KhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-client-32.png"))); // NOI18N
        lbl_KhachHang.setText("Khách Hàng");
        lbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout KhachHangLayout = new javax.swing.GroupLayout(KhachHang);
        KhachHang.setLayout(KhachHangLayout);
        KhachHangLayout.setHorizontalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KhachHangLayout.setVerticalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        KhuyenMai.setBackground(new java.awt.Color(73, 186, 245));
        KhuyenMai.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_KhuyenMai.setBackground(new java.awt.Color(73, 186, 245));
        lbl_KhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_KhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_KhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-voucher-32.png"))); // NOI18N
        lbl_KhuyenMai.setText("Khuyến Mãi");
        lbl_KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhuyenMaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout KhuyenMaiLayout = new javax.swing.GroupLayout(KhuyenMai);
        KhuyenMai.setLayout(KhuyenMaiLayout);
        KhuyenMaiLayout.setHorizontalGroup(
            KhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KhuyenMaiLayout.setVerticalGroup(
            KhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        ThongKe.setBackground(new java.awt.Color(73, 186, 245));
        ThongKe.setPreferredSize(new java.awt.Dimension(0, 57));

        lbl_thongke.setBackground(new java.awt.Color(73, 186, 245));
        lbl_thongke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_thongke.setForeground(new java.awt.Color(255, 255, 255));
        lbl_thongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rank.png"))); // NOI18N
        lbl_thongke.setText("Thống Kê");
        lbl_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_thongkeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_thongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Nhân Viên ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Show.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Show.setPreferredSize(new java.awt.Dimension(960, 650));
        Panel_Show.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Panel_Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_TrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TrangchuMouseClicked
        // Click trang chủ 
        setColorJpanel(Trangchu);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_Trangchu);

        resetColor(lbl_thongke);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new TrangChuView());
    }//GEN-LAST:event_lbl_TrangchuMouseClicked

    private void lbl_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BanHangMouseClicked
        // Click bán hàng 
        setColorJpanel(BanHang);
        resetColorJpane(Trangchu);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_BanHang);

        resetColor(lbl_Trangchu);
        resetColor(lbl_thongke);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new BanHangView());
    }//GEN-LAST:event_lbl_BanHangMouseClicked

    private void lbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SanPhamMouseClicked
        // Click sản phẩm 
        setColorJpanel(SanPham);
        resetColorJpane(BanHang);
        resetColorJpane(Trangchu);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_SanPham);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_thongke);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new SanPhamView());
    }//GEN-LAST:event_lbl_SanPhamMouseClicked

    private void lbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HoaDonMouseClicked
        // Click hóa đơn 
        setColorJpanel(HoaDon);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(Trangchu);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_HoaDon);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_thongke);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new HoaDonView());
    }//GEN-LAST:event_lbl_HoaDonMouseClicked

    private void lbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseClicked
        // Click Nhân Viên 
        setColorJpanel(NhanVien);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(Trangchu);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_NhanVien);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_thongke);
        resetColor(lbl_KhuyenMai);
        showPanel(new NhanVienView());
    }//GEN-LAST:event_lbl_NhanVienMouseClicked

    private void lbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseClicked
        // CLick khách hàng 
        setColorJpanel(KhachHang);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(Trangchu);
        resetColorJpane(KhuyenMai);
        resetColorJpane(ThongKe);
        setColor(lbl_KhachHang);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_thongke);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new KhachHangView());
    }//GEN-LAST:event_lbl_KhachHangMouseClicked

    private void lbl_KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhuyenMaiMouseClicked
        // Click khuyến mãi 
        setColorJpanel(KhuyenMai);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(Trangchu);
        resetColorJpane(ThongKe);
        setColor(lbl_KhuyenMai);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_thongke);
        showPanel(new KhuyenMaiView());
    }//GEN-LAST:event_lbl_KhuyenMaiMouseClicked

    private void lbl_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_thongkeMouseClicked
        // CLick thống kê 
        setColorJpanel(ThongKe);
        resetColorJpane(BanHang);
        resetColorJpane(SanPham);
        resetColorJpane(HoaDon);
        resetColorJpane(NhanVien);
        resetColorJpane(KhachHang);
        resetColorJpane(KhuyenMai);
        resetColorJpane(Trangchu);
        setColor(lbl_thongke);

        resetColor(lbl_Trangchu);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new ThongKeView());
    }//GEN-LAST:event_lbl_thongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BanHang;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel KhachHang;
    private javax.swing.JPanel KhuyenMai;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel Panel_Show;
    private javax.swing.JPanel SanPham;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel Trangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_BanHang;
    private javax.swing.JLabel lbl_HoaDon;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_KhuyenMai;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_SanPham;
    private javax.swing.JLabel lbl_Trangchu;
    private javax.swing.JLabel lbl_thongke;
    // End of variables declaration//GEN-END:variables

    public void setColorJpanel(JPanel pane) {
        pane.setBackground(new java.awt.Color(25, 142, 212));
    }

    public void resetColorJpane(JPanel pane) {
        pane.setBackground(new java.awt.Color(73, 186, 245));
    }

    public void setColor(JLabel label) {
        label.setForeground(Color.black);
    }

    public void resetColor(JLabel label) {
        label.setForeground(Color.white);
    }

    public void showPanel(JPanel panel) {
        Panel_Show.removeAll();
        Panel_Show.add(panel);
        Panel_Show.revalidate();
    }

}
